security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: doctrine
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/AdminControllers, roles: ROLE_ADMIN }
